### ISSUE TITLE
Cleanup doesn't clean pycache 

### ISSUE THREAD

**Issue by blhagadorn** [kdenhartog/Indy-dev#8]
Stale bytecode is left even after total cleanup from running the getting started in the `python/src/__pycache__` and then trying the how-to's
I'm guessing it's a problem around these errors shown in tests, where the python doesn't follow the rust version of the teardown:
```        #[test]
        fn indy_create_wallet_works_for_missed_key() {
            utils::setup();

            let res = wallet::create_wallet(WALLET_CONFIG, r#"{}"#);
            assert_eq!(res.unwrap_err(), ErrorCode::CommonInvalidStructure);

            utils::tear_down();
        }

        #[test]
        fn indy_create_wallet_works_for_empty_name() {
            utils::setup();

            let res = wallet::create_wallet(r#"{"id": ""}"#, WALLET_CREDENTIALS);
            assert_eq!(res.unwrap_err(), ErrorCode::CommonInvalidStructure);

            utils::tear_down();
        }

        #[test]
        fn indy_create_wallet_works_for_raw_key_invalid_length() {
            test::cleanup_storage();

            let credentials = json!({"key": "key", "key_derivation_method": "RAW"}).to_string();
            let res = wallet::create_wallet(WALLET_CONFIG, &credentials);
            assert_eq!(res.unwrap_err(), ErrorCode::CommonInvalidStructure);

            test::cleanup_storage();
        }
```
Solution: cleanup pycache after running `gettingstarted.py` as well as makefile cleaning that up as well:

_indy_loop_callback: Function returned error 113
Error occurred: ErrorCode.CommonInvalidStructure

**Comment by kdenhartog** [comment]
fixed this with the new make refresh command.

**Comment by blhagadorn** [comment]
Alright I think the 

> CommonInvalidStructure

 keeps coming up so this solved the pycache but that error remains.

**Comment by blhagadorn** [comment]
Thanks@
